name: TestingFrontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Start the application
        run: yarn start
        env:
          CI: true

      - name: Run Cypress tests
        run: yarn cy:run
        env:
          CYPRESS_BASE_URL: http://localhost:5173

      # Upload Cypress videos and screenshots only if tests fail
      - name: Upload Cypress videos and screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
